name: Documents

on:
  push:
    branches:
      - main

jobs:
  documents:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up nodejs
        uses: actions/setup-node@v4
        with:
          node-version: current

      - name: Install Dependencies
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
          pnpm config set store-dir .pnpm-store
          pnpm install

      - name: Build Documentation
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
          pnpm docs:build
